language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm install -g codecov
  - npm install -g semantic-release
script:
  - npm run test
  - npm run lint
  - npm run flow
after_success:
  - codecov
  - npm run semantic-release
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: 'docs'
  on:
    branch: master
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
